[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
    "alacritty_config",
    "alacritty_config_derive",
]
resolver = "2"

[profile.release]
lto = "thin"
debug = 1
incremental = false

[replace]
"vte:0.11.1" = { git = 'https://github.com/gulrotkake/vte-decps' }
